services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - meu-volume:/var/opt/mssql

volumes:
  meu-volume:
